### ISSUE TITLE
[Enhancement] Log Levels

### ISSUE THREAD

**Issue by NekoShinobi** [marton-demeter/logger-md#1]
- Allow user to set what level of logger to use.

If Level is set to log.WARNING, it should only output WARNING and CRITICAL messages.

😄

**Comment by marton-demeter** [comment]
Added log.update.level(LEVEL) w/ LEVEL being:
- log.DEBUG
- log.INFO
- log.SUCCESS
- log.WARNING
- log.ERROR

If a level is specified all higher levels will be displayed. For example if the logger is operating at WARNING level, only WARNING and ERROR messages will be logged.

The default level is DEBUG.
